### ISSUE TITLE
Proxy

### ISSUE THREAD

**Issue by danielhaas** [svenkubiak/JPushover#2]
Could you please add the support for a proxy. 

It's just adding to the Request.viaProxy(String or HttpHost) in line 250 in JPushover class.

**Comment by danielhaas** [comment]
Have written something and made a pull request

**Comment by danielhaas** [comment]
It would be nice if it would be in the maven version

**Comment by svenkubiak** [comment]
2.1.4 is released. Should be on maven central soon.
