### ISSUE TITLE
URL & URL Title Broken, undesired output

### ISSUE THREAD

**Issue by jlhudson** [svenkubiak/JPushover#5]
When creating a new Message,  I omit the URL & URL Title as they aren't required, yet the message delivered contains a "Open null" weblink.
In addition, it seems providing a URL Title, doesn't set the URL title on the delivered link.  It is displayed as "Open www.url.com"

**Comment by svenkubiak** [comment]
Thanks for reporting this.
URL and URL title was actually set incorrectly. I have just released a fix which should be on Maven central soon.

**Comment by jlhudson** [comment]
I may not have highlighted the error enough.  

If the User sets NO url.  (ie, doesn't use .withUrl or .withUrlTitle) your program stills sends a null value through to pushover. This results in a weblink attached to the pushover message, which links to null. 

I'd suggest a NULL check for both UrlTitle & Url before adding them to the PushoverUrlMessage

**Comment by svenkubiak** [comment]
Ok. New release is out.
