### ISSUE TITLE
Open Client API Documentation

### ISSUE THREAD

**Issue by jlhudson** [svenkubiak/JPushover#6]
In your ReadMe, I believe you have a copy and paste error. 

> //4 - Parse deviceId from JSON response and store it
> String deviceId = MyJsonParser(pushoverResponse.getResponse());
> 
> //5 - Create a new class
> String deviceId = MyJsonParser(pushoverResponse.getResponse());

Is there any chance of also proving a snipped of code for downlaoding pending messages from the pushover server.

**Comment by svenkubiak** [comment]
You are correct, there was a copy&paste error. I have updated the read.me accordingly.

Messages can be fetched using secret and deviceid.

`JPushover.openClientAPI().messages(secret, deviceId);
`
